/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LoggingTest;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class App {
    public static Logger logger = LogManager.getLogger("App");

    private static String getGreeting(String name) {
        logger.traceEntry("getGreeting({})", name);

        return logger.traceExit("Hello, " + name + "!");
    }

    public static void main(String[] args) {
        logger.traceEntry();
        logger.info(getGreeting("Sam"));
        logger.info(getGreeting("Alice"));
        logger.traceExit();
    }
}
